### ISSUE TITLE
Testing on Laravel 5 - issue with contract instantiation

### ISSUE THREAD

**Issue by kirkbushell** [orchestral/testbench#74]
This is the bug I'm currently getting running on the 3.0.x@dev:

Illuminate\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in vendor/laravel/framework/src/Illuminate/Container/Container.php on line 792

**Comment by crynobone** [comment]
Can you test above change

**Comment by kirkbushell** [comment]
Works - great job :)

**Comment by kirkbushell** [comment]
And wow at your fast response! Good stuff man!

**Comment by vluzrmos** [comment]
I'm having that issue too, I'm using ~3.1 dev.

**Comment by vluzrmos** [comment]
it happens when I try to do:

```
view('name', [parameters])->render();
```

**Comment by vluzrmos** [comment]
Stack trace:

```
PHPUnit_Framework_Exception: PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php:730
Stack trace:
#0 /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php(612): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(148): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /home/vluzrmos/ in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 730

Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 730

Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 730

Call Stack:
    0.5632   29936272   1. Illuminate\Foundation\Bootstrap\HandleExceptions->handleException() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:0
    0.5632   29936320   2. Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:73
    0.5632   29936432   3. Illuminate\Foundation\Application->make() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:148
    0.5632   29936568   4. Illuminate\Container\Container->make() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
    0.5633   29936568   5. Illuminate\Container\Container->build() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php:612

PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php:730
Stack trace:
#0 /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php(612): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(148): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /home/vluzrmos/ in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 730

Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 730

Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 730

Call Stack:
    0.5638   29962856   1. Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:0
    0.5643   30004152   2. Illuminate\Foundation\Bootstrap\HandleExceptions->handleException() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:112
    0.5643   30004152   3. Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:73
    0.5643   30004264   4. Illuminate\Foundation\Application->make() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:148
    0.5643   30004400   5. Illuminate\Container\Container->make() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
    0.5643   30004400   6. Illuminate\Container\Container->build() /home/vluzrmos/PhpstormProjects/defender-dashboard/workbench/artesaos/defender/vendor/laravel/framework/src/Illuminate/Container/Container.php:612
```

**Comment by crynobone** [comment]
@vluzrmos 

Don't just continue on a closed issue and assume you have the same problem as someone else especially when this has been closed for months. 

Create a new issue with full error stack trace.
